# Generated by Django 3.0.5 on 2020-05-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gameLink',
            field=models.CharField(default='default value', max_length=500),
        ),
    ]
