# Generated by Django 3.0.5 on 2020-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_gamelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gameLink',
            field=models.FilePathField(default='default value', path='gamepage/templates/gamepage'),
        ),
    ]
