# Generated by Django 3.0.5 on 2020-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200516_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gameLink',
            field=models.FilePathField(default='default value', path='media/gamepage'),
        ),
    ]
