# Generated by Django 3.0.5 on 2020-05-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200516_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gameLink',
        ),
    ]
