# Generated by Django 3.0.5 on 2020-05-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200517_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(default='null', through='post.Tagging', to='post.Tag'),
        ),
    ]
