# Generated by Django 3.0.5 on 2020-05-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20200517_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='taggings',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tagging',
        ),
    ]
