# Generated by Django 3.0.5 on 2020-05-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200426_1506'),
        ('post', '0016_auto_20200518_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank='Null', on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
