# Generated by Django 3.0.5 on 2020-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200426_1506'),
        ('post', '0019_auto_20200521_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='accounts.UserProfile'),
        ),
    ]
