# Generated by Django 3.0.5 on 2020-05-22 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0023_remove_post_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
