# Generated by Django 3.0.5 on 2020-04-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_phone',
            field=models.CharField(max_length=11),
        ),
    ]
