# Generated by Django 3.0.5 on 2020-04-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200426_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
